### ISSUE TITLE
Issues to solve

### ISSUE THREAD

**Issue by pkuerljh** [hanjii-open/jufaanli#1]
【六个Crime共同的问题】
1.	“审理程序”只需要“一审”
2.	“有期徒刑年数（刑期）”这一栏留下，作为裁判文书的原文，原始数据。然后以“有期徒刑年数（刑期）”为基础，增加一个变量“有期徒刑以天为单位”，将有期徒刑年数格式化，每个月记为30天，例如一年=360，两年=720，三年九个月=1350，七个月十五天=225等。
3.	“缓刑长度” 这一栏留下，作为裁判文书的原文，原始数据。然后以“缓刑长度”为基础，增加一个变量“缓刑刑期”， 将缓刑刑期格式化，每个月记为30天，例如一年=360，两年=720，三年九个月=1350，七个月十五天=225等。
4.	“罚金数额”，万元、元单位不统一，希望全都改成的以元为单位的数字模式，如果有多个数额则相加，不要留逗号。
5.	“判决时间”的格式现在是“2009-01-01”，可否改为“20090101”这种格式？

【Crime1 非法吸收公众存款罪】
1.	吸收公众存款的数额：表格里全都显示吸，吸收应该是有问题。
2.	给集资参与人造成直接经济损失的数额：万元，元单位不统一，希望全都改成的以元为单位的数字模式，如果有多个数额则相加，不要留逗号。
3.	加一个变量：是否判处罚金，判断规则是，只要判决书里出现了“罚金”这两个字，则为“是”，否则为“否”。
【Crime2 诈骗罪】
1.	诈骗数额：
之前写的提取规则是：在“经审理查明”和“本院认为“之间的几段话，一般会出现“骗取……元”，这句话，只要提取这句话中的数字即可，有时候会出现“万元”的情况，这个“万”也需要提取到。然后有的判决书会出现两次以上“骗取……元”，就把每一句话都提取，然后把这些数字加起来就好。
现在加上：如果出现了两次以上，骗取……元，数额是一样的话，就只提一个就好。比如说55万出现了两次，那就只提取一次55万，因为第二次出现大概率是重复。
2.	“拘役时长”，这个变量也保留作为原始文本，然后增加一个变量“拘役刑期”，将拘役时长格式化，每个月记为30天，例如1个月=30天，2个月=60天等。
【Crime3 强奸罪】
1.	增加变量“是否造成轻微伤”
2.	增加变量“是否造成轻伤”
3.	增加变量“是否造成重伤”
以上三者的提取规则都是，文书全文中如果分别出现“轻微伤”“轻伤”“重伤”，则为“是”，否则为“否”。
【Crime4 妨害公务罪】
1.	“轻伤人数”和“轻微伤人数”，有的地方出现了汉字，不知道是不是代码出现了问题。（不过这个解决起来如果麻烦的话也没关系）
2.	“拘役月数”，这个变量也保留作为原始文本，然后增加一个变量“拘役刑期”，将拘役时长格式化，每个月记为30天，例如1个月=30天，2个月=60天等。
【Crime5 醉酒型危险驾驶罪】
1.	血液中酒精浓度提取效果不佳，但是我检查了一下文书，之前写的提取规则是：全文中出现“含量”这个词，“含量”这个词后面出XXX mg/100ml，这个XXX就是要提取的数字”，我检查了一下文书，未被提取的文书中，也是符合这个规则的，是不是代码没办法实现这个规则？是否需要另换规则？
2.	“拘役月数”，这个变量也保留作为原始文本，然后增加一个变量“拘役刑期”，将拘役时长格式化，每个月记为30天，例如1个月=30天，2个月=60天等。
【Crime6 掩饰、隐瞒犯罪所得、犯罪所得收益罪罪】
1.	“掩饰、隐瞒犯罪所得、犯罪所得收益的价值总额”，这个要提取，提取规则：“指控”开始的那段，出现，“价值人民币XXX元”或者“价值XXX元”，这里的XXX就是价值总额。

**Comment by obnijnil** [comment]
关于 *【六个Crime共同的问题】*

> “审理程序”只需要“一审”

不知道 *一审* 的数量有多少，不过够用就行。

> “有期徒刑年数（刑期）”这一栏留下...

*Crime5* 你原来写的是没有 *有期徒刑年数* 的，也需要加上是吧？

ps 不同问题你可以单独创建 issue，这样可以分开跟进。

**Comment by pkuerljh** [comment]
抱歉，crime5不需要有期徒刑年数（因为crime5 比较特殊，我们国家的危险驾驶罪，最高刑罚只有拘役，有期徒刑是一种比拘役高的刑期~~: D) 谢谢~~ 那我现在重新写一下issue哦~~
