### ISSUE TITLE
issue14：crime5 “血液中酒精浓度”

### ISSUE THREAD

**Issue by pkuerljh** [hanjii-open/jufaanli#15]
血液中酒精浓度提取效果不佳，但是我检查了一下文书，之前写的提取规则是：全文中出现“含量”这个词，“含量”这个词后面出XXX mg/100ml，这个XXX就是要提取的数字”，我检查了一下文书，未被提取的文书中，也是符合这个规则的，是不是代码没办法实现这个规则？是否需要另换规则？

**Comment by obnijnil** [comment]
给写成从 *法院认为* （即 conclusion）里提取了，已修改。
