### ISSUE TITLE
issue2: 增加变量“有期徒刑以天为单位”

### ISSUE THREAD

**Issue by pkuerljh** [hanjii-open/jufaanli#3]
除了crime5以外，其余的5个crime，“有期徒刑年数（刑期）”这一栏留下，作为裁判文书的原文，原始数据。然后以“有期徒刑年数（刑期）”为基础，增加一个变量“有期徒刑以天为单位”，将有期徒刑年数格式化，每个月记为30天，例如一年=360，两年=720，三年九个月=1350，七个月十五天=225等。

**Comment by obnijnil** [comment]
一年不记为 **365** 吗？（还是说为了方便计算）

**Comment by pkuerljh** [comment]
为了方便计算，以360为单位即可
